// <auto-generated />
using ABC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABC.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231003124755_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ABC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "CCTV"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Computer Accesories"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Cables & Tools"
                        });
                });

            modelBuilder.Entity("ABC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CostPrice")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumStockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RetailPrice")
                        .HasColumnType("real");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Xiaomi",
                            CostPrice = 1000f,
                            Description = "128GB can record 16 days of video",
                            MinimumStockQuantity = 3,
                            Name = "V380 P2 HD 1080 IP Camera Wifi Wireless Output",
                            RetailPrice = 1700f,
                            SKU = "cctv-P2-Wireless-1080P",
                            StockQuantity = 20,
                            Supplier = "business corp"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            CostPrice = 1200f,
                            Description = "Panoramic view with motion detection",
                            MinimumStockQuantity = 4,
                            Name = "SmartCam 360 Security Camera",
                            RetailPrice = 1999f,
                            SKU = "cctv-SmartCam-360",
                            StockQuantity = 15,
                            Supplier = "Tech Solutions Ltd."
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Google Nest",
                            CostPrice = 1500f,
                            Description = "Weatherproof, 4K UHD video recording",
                            MinimumStockQuantity = 5,
                            Name = "Nest Cam Outdoor 4K Security Camera",
                            RetailPrice = 2499f,
                            SKU = "cctv-NestCam-Outdoor-4K",
                            StockQuantity = 25,
                            Supplier = "Smart Home Innovations"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Hikvision",
                            CostPrice = 900f,
                            Description = "High-resolution dome camera with night vision",
                            MinimumStockQuantity = 2,
                            Name = "Hikvision DS-2CE56H0T-ITPF 5MP Dome Camera",
                            RetailPrice = 1499f,
                            SKU = "cctv-Hikvision-5MP-Dome",
                            StockQuantity = 18,
                            Supplier = "Security World"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Arlo",
                            CostPrice = 1100f,
                            Description = "Wire-free, 2K HDR video with integrated spotlight",
                            MinimumStockQuantity = 4,
                            Name = "Arlo Pro 4 Spotlight Camera",
                            RetailPrice = 1799f,
                            SKU = "cctv-Arlo-Pro-4",
                            StockQuantity = 22,
                            Supplier = "Home Security Plus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
